# Generated by Django 4.2 on 2026-02-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0002_passwordresetotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardwareassignment",
            name="exam_city",
            field=models.CharField(
                blank=True,
                help_text="City where the employee will take the exam",
                max_length=200,
                null=True,
            ),
        ),
    ]
