# Generated by Django 4.2 on 2026-04-04 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0003_hardwareassignment_exam_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeHardwareTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("from_exam_city", models.CharField(max_length=200)),
                ("to_exam_city", models.CharField(max_length=200)),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("temporary", "Temporary Transfer"),
                            ("permanent", "Permanent Transfer"),
                        ],
                        default="temporary",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("expected_return_date", models.DateField(blank=True, null=True)),
                ("requested_date", models.DateTimeField(auto_now_add=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("transfer_date", models.DateField(blank=True, null=True)),
                ("expected_arrival_date", models.DateField()),
                ("actual_arrival_date", models.DateField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Transfer Requested"),
                            ("approved_by_manager", "Approved by Manager"),
                            ("in_transit", "In Transit"),
                            ("received_by_receiver", "Received by Receiver"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("condition_before", models.TextField(blank=True, null=True)),
                ("condition_after", models.TextField(blank=True, null=True)),
                (
                    "delivery_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("requester_notes", models.TextField(blank=True, null=True)),
                ("manager_notes", models.TextField(blank=True, null=True)),
                ("completion_notes", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_approved_emp",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_created_emp",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_from_emp",
                        to="hardware_management.project",
                    ),
                ),
                (
                    "hardware_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_transfers",
                        to="hardware_management.hardware",
                    ),
                ),
                (
                    "to_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_to_emp",
                        to="hardware_management.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="hardware_management.employeehardwaretransfer",
                    ),
                ),
            ],
        ),
    ]
