# Generated by Django 4.2 on 2026-04-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0004_employeehardwaretransfer_transfernotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="current_exam_city",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
