# Generated by Django 4.2 on 2026-04-04 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0005_customuser_current_exam_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="current_exam_city",
        ),
    ]
