# Generated by Django 4.2 on 2026-04-04 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0006_remove_customuser_current_exam_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardware",
            name="employee",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="HardwareType",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
