# Generated by Django 4.2 on 2026-04-04 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0008_transferhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeehardwaretransfer",
            name="condition_after",
        ),
        migrations.RemoveField(
            model_name="employeehardwaretransfer",
            name="condition_before",
        ),
        migrations.RemoveField(
            model_name="employeehardwaretransfer",
            name="hardware_item",
        ),
        migrations.AddField(
            model_name="transferhistory",
            name="action",
            field=models.CharField(default="action", max_length=100),
        ),
        migrations.CreateModel(
            name="TransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_transit", "In Transit"),
                            ("received", "Received"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("condition_before", models.TextField(blank=True, null=True)),
                ("condition_after", models.TextField(blank=True, null=True)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("transfer_date", models.DateField(blank=True, null=True)),
                ("received_date", models.DateField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hardware",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hardware_management.hardware",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_items",
                        to="hardware_management.employeehardwaretransfer",
                    ),
                ),
            ],
            options={
                "unique_together": {("transfer", "hardware")},
            },
        ),
        migrations.AddField(
            model_name="employeehardwaretransfer",
            name="hardware_items",
            field=models.ManyToManyField(
                related_name="employee_transfers",
                through="hardware_management.TransferItem",
                to="hardware_management.hardware",
            ),
        ),
    ]
