# Generated by Django 4.2 on 2026-05-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0010_chatbotconversation"),
    ]

    operations = [
        migrations.CreateModel(
            name="HardwareKnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hardware", "Hardware Info"),
                            ("procedure", "Procedure"),
                            ("faq", "FAQ"),
                            ("policy", "Policy"),
                        ],
                        default="hardware",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="chatbotconversation",
            name="response_time",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="chatbotconversation",
            name="tokens_used",
            field=models.IntegerField(default=0),
        ),
    ]
