# Generated by Django 4.2 on 2026-05-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0011_hardwareknowledgebase_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatbotconversation",
            name="response_time",
        ),
        migrations.RemoveField(
            model_name="chatbotconversation",
            name="tokens_used",
        ),
    ]
